/*
 * Created on 20-Aug-2005
 */
package com.ixora.rms.agents.wmi;

/**
 * HierarchyDefinition
 * Holds group hierarchy for WMI classes
 */
public class HierarchyDefinition {
	public static String[] getWMIStructure(String namespace) {
		if (namespace.equalsIgnoreCase("root\\cimv2")) {
			return new String[] {
				"wmi_hw/hw_cooling/Win32_Fan",
				"wmi_hw/hw_cooling/Win32_HeatPipe",
				"wmi_hw/hw_cooling/Win32_Refrigeration",
				"wmi_hw/hw_cooling/Win32_TemperatureProbe",

				"wmi_hw/hw_input/Win32_Keyboard",
				"wmi_hw/hw_input/Win32_PointingDevice",

				"wmi_hw/hw_storage/Win32_AutochkSetting",
				"wmi_hw/hw_storage/Win32_CDROMDrive",
				"wmi_hw/hw_storage/Win32_DiskDrive",
				"wmi_hw/hw_storage/Win32_FloppyDrive",
				"wmi_hw/hw_storage/Win32_PhysicalMedia",
				"wmi_hw/hw_storage/Win32_TapeDrive",

				"wmi_hw/hw_mb/Win32_1394Controller",
				"wmi_hw/hw_mb/Win32_BaseBoard",
				"wmi_hw/hw_mb/Win32_BIOS",
				"wmi_hw/hw_mb/Win32_Bus",
				"wmi_hw/hw_mb/Win32_CacheMemory",
				"wmi_hw/hw_mb/Win32_ControllerHasHub",
				"wmi_hw/hw_mb/Win32_DeviceMemoryAddress",
				"wmi_hw/hw_mb/Win32_DMAChannel",
				"wmi_hw/hw_mb/Win32_FloppyController",
				"wmi_hw/hw_mb/Win32_IDEController",
				"wmi_hw/hw_mb/Win32_InfraredDevice",
				"wmi_hw/hw_mb/Win32_IRQResource",
				"wmi_hw/hw_mb/Win32_MemoryArray",
				"wmi_hw/hw_mb/Win32_MemoryDevice",
				"wmi_hw/hw_mb/Win32_MotherboardDevice",
				"wmi_hw/hw_mb/Win32_OnBoardDevice",
				"wmi_hw/hw_mb/Win32_ParallelPort",
				"wmi_hw/hw_mb/Win32_PCMCIAController",
				"wmi_hw/hw_mb/Win32_PhysicalMemory",
				"wmi_hw/hw_mb/Win32_PhysicalMemoryArray",
				"wmi_hw/hw_mb/Win32_PNPAllocatedResource",
				"wmi_hw/hw_mb/Win32_PNPEntity",
				"wmi_hw/hw_mb/Win32_PortConnector",
				"wmi_hw/hw_mb/Win32_PortResource",
				"wmi_hw/hw_mb/Win32_Processor",
				"wmi_hw/hw_mb/Win32_SCSIController",
				"wmi_hw/hw_mb/Win32_SerialPort",
				"wmi_hw/hw_mb/Win32_SerialPortConfiguration",
				"wmi_hw/hw_mb/Win32_SMBIOSMemory",
				"wmi_hw/hw_mb/Win32_SoundDevice",
				"wmi_hw/hw_mb/Win32_SystemEnclosure",
				"wmi_hw/hw_mb/Win32_SystemMemoryResource",
				"wmi_hw/hw_mb/Win32_SystemSlot",
				"wmi_hw/hw_mb/Win32_USBController",
				"wmi_hw/hw_mb/Win32_USBHub",

				"wmi_hw/hw_net/Win32_NetworkAdapter",
				"wmi_hw/hw_net/Win32_NetworkAdapterConfiguration",

				"wmi_hw/hw_power/Win32_Battery",
				"wmi_hw/hw_power/Win32_CurrentProbe",
				"wmi_hw/hw_power/Win32_PortableBattery",
				"wmi_hw/hw_power/Win32_PowerManagementEvent",
				"wmi_hw/hw_power/Win32_UninterruptiblePowerSupply",
				"wmi_hw/hw_power/Win32_VoltageProbe",

				"wmi_hw/hw_print/Win32_Printer",
				"wmi_hw/hw_print/Win32_PrinterConfiguration",
				"wmi_hw/hw_print/Win32_PrinterDriver",
				"wmi_hw/hw_print/Win32_PrintJob",
				"wmi_hw/hw_print/Win32_TCPIPPrinterPort",

				"wmi_hw/hw_telephony/Win32_POTSModem",

				"wmi_hw/hw_video/Win32_DesktopMonitor",
				"wmi_hw/hw_video/Win32_DisplayConfiguration",
				"wmi_hw/hw_video/Win32_DisplayControllerConfiguration",
				"wmi_hw/hw_video/Win32_VideoConfiguration",
				"wmi_hw/hw_video/Win32_VideoController",

				"wmi_os/os_COM/Win32_ClassicCOMClass",
				"wmi_os/os_COM/Win32_COMApplication",
				"wmi_os/os_COM/Win32_COMClass",
				"wmi_os/os_COM/Win32_ComponentCategory",
				"wmi_os/os_COM/Win32_COMSetting",
				"wmi_os/os_COM/Win32_DCOMApplication",
				"wmi_os/os_COM/Win32_DCOMApplicationSetting",

				"wmi_os/os_desktop/Win32_Desktop",
				"wmi_os/os_desktop/Win32_Environment",
				"wmi_os/os_desktop/Win32_TimeZone",

				"wmi_os/os_drivers/Win32_DriverVXD",
				"wmi_os/os_drivers/Win32_SystemDriver",

				"wmi_os/os_fs/Win32_Directory",
				"wmi_os/os_fs/Win32_DirectorySpecification",
				"wmi_os/os_fs/Win32_DiskPartition",
				"wmi_os/os_fs/Win32_LogicalDisk",
				"wmi_os/os_fs/Win32_MappedLogicalDisk",
				"wmi_os/os_fs/Win32_QuotaSetting",
				"wmi_os/os_fs/Win32_ShortcutFile",
				"wmi_os/os_fs/Win32_Volume",

				"wmi_os/os_jobs/Win32_LUID",
				"wmi_os/os_jobs/Win32_LUIDandAttributes",
				"wmi_os/os_jobs/Win32_NamedJobObject",
				"wmi_os/os_jobs/Win32_NamedJobObjectActgInfo",
				"wmi_os/os_jobs/Win32_NamedJobObjectLimit",
				"wmi_os/os_jobs/Win32_NamedJobObjectLimitSetting",
				"wmi_os/os_jobs/Win32_NamedJobObjectProcess",
				"wmi_os/os_jobs/Win32_NamedJobObjectSecLimit",
				"wmi_os/os_jobs/Win32_NamedJobObjectSecLimitSetting",
				"wmi_os/os_jobs/Win32_NamedJobObjectStatistics",
				"wmi_os/os_jobs/Win32_SIDandAttributes",
				"wmi_os/os_jobs/Win32_TokenGroups",
				"wmi_os/os_jobs/Win32_TokenPrivileges",

				"wmi_os/os_memory/Win32_LogicalMemoryConfiguration",
				"wmi_os/os_memory/Win32_PageFile",
				"wmi_os/os_memory/Win32_PageFileSetting",
				"wmi_os/os_memory/Win32_PageFileUsage",

				"wmi_os/os_multimedia/Win32_CodecFile",

				"wmi_os/os_net/Win32_IP4PersistedRouteTable",
				"wmi_os/os_net/Win32_IP4RouteTable",
				"wmi_os/os_net/Win32_IP4RouteTableEvent",
				"wmi_os/os_net/Win32_NetworkClient",
				"wmi_os/os_net/Win32_NetworkConnection",
				"wmi_os/os_net/Win32_NetworkProtocol",
				"wmi_os/os_net/Win32_NTDomain",
				"wmi_os/os_net/Win32_PingStatus",

				"wmi_os/os_events/Win32_ComputerShutdownEvent",
				"wmi_os/os_events/Win32_ComputerSystemEvent",
				"wmi_os/os_events/Win32_DeviceChangeEvent",
				"wmi_os/os_events/Win32_ModuleLoadTrace",
				"wmi_os/os_events/Win32_ModuleTrace",
				"wmi_os/os_events/Win32_ProcessStartTrace",
				"wmi_os/os_events/Win32_ProcessStopTrace",
				"wmi_os/os_events/Win32_ProcessTrace",
				"wmi_os/os_events/Win32_SystemConfigurationChangeEvent",
				"wmi_os/os_events/Win32_SystemTrace",
				"wmi_os/os_events/Win32_ThreadStartTrace",
				"wmi_os/os_events/Win32_ThreadStopTrace",
				"wmi_os/os_events/Win32_ThreadTrace",
				"wmi_os/os_events/Win32_VolumeChangeEvent",

				"wmi_os/os_settings/Win32_BootConfiguration",
				"wmi_os/os_settings/Win32_ComputerSystem",
				"wmi_os/os_settings/Win32_ComputerSystemProduct",
				"wmi_os/os_settings/Win32_LoadOrderGroup",
				"wmi_os/os_settings/Win32_LoadOrderGroupServiceDependencies",
				"wmi_os/os_settings/Win32_OperatingSystem",
				"wmi_os/os_settings/Win32_OSRecoveryConfiguration",
				"wmi_os/os_settings/Win32_QuickFixEngineering",
				"wmi_os/os_settings/Win32_StartupCommand",

				"wmi_os/os_processes/Win32_Process",
				"wmi_os/os_processes/Win32_ProcessStartup",
				"wmi_os/os_processes/Win32_Thread",

				"wmi_os/os_registry/Win32_Registry",

				"wmi_os/os_scheduler/Win32_CurrentTime",
				"wmi_os/os_scheduler/Win32_ScheduledJob",

				"wmi_os/os_security/Win32_ACE",
				"wmi_os/os_security/Win32_LogicalFileSecuritySetting",
				"wmi_os/os_security/Win32_LogicalShareSecuritySetting",
				"wmi_os/os_security/Win32_PrivilegesStatus",
				"wmi_os/os_security/Win32_SecurityDescriptor",
				"wmi_os/os_security/Win32_SecuritySetting",
				"wmi_os/os_security/Win32_SecuritySettingAccess",
				"wmi_os/os_security/Win32_SecuritySettingAuditing",
				"wmi_os/os_security/Win32_SecuritySettingOfLogicalFile",
				"wmi_os/os_security/Win32_SecuritySettingOfLogicalShare",
				"wmi_os/os_security/Win32_SID",
				"wmi_os/os_security/Win32_Trustee",

				"wmi_os/os_services/Win32_BaseService",
				"wmi_os/os_services/Win32_Service",

				"wmi_os/os_shares/Win32_ServerConnection",
				"wmi_os/os_shares/Win32_ServerSession",
				"wmi_os/os_shares/Win32_Share",

				"wmi_os/os_startmenu/Win32_LogicalProgramGroup",
				"wmi_os/os_startmenu/Win32_LogicalProgramGroupItem",
				"wmi_os/os_startmenu/Win32_ProgramGroup",
				"wmi_os/os_startmenu/Win32_ProgramGroupOrItem",

				"wmi_os/os_storage/Win32_ShadowCopy",
				"wmi_os/os_storage/Win32_Volume",

				"wmi_os/os_users/Win32_Account",
				"wmi_os/os_users/Win32_Group",
				"wmi_os/os_users/Win32_LogonSession",
				"wmi_os/os_users/Win32_LogonSessionMappedDisk",
				"wmi_os/os_users/Win32_NetworkLoginProfile",
				"wmi_os/os_users/Win32_SystemAccount",
				"wmi_os/os_users/Win32_UserAccount",

				"wmi_os/os_eventlog/Win32_NTEventlogFile",
				"wmi_os/os_eventlog/Win32_NTLogEvent",

				"wmi_os/os_wpa/Win32_Proxy",
				"wmi_os/os_wpa/Win32_WindowsProductActivation",

				"wmi_app/Win32_ApplicationService",
				"wmi_app/Win32_Binary",
				"wmi_app/Win32_BindImageAction",
				"wmi_app/Win32_ClassInfoAction",
				"wmi_app/Win32_CommandLineAccess",
				"wmi_app/Win32_Condition",
				"wmi_app/Win32_CreateFolderAction",
				"wmi_app/Win32_DuplicateFileAction",
				"wmi_app/Win32_EnvironmentSpecification",
				"wmi_app/Win32_ExtensionInfoAction",
				"wmi_app/Win32_FileSpecification",
				"wmi_app/Win32_FontInfoAction",
				"wmi_app/Win32_IniFileSpecification",
				"wmi_app/Win32_LaunchCondition",
				"wmi_app/Win32_MIMEInfoAction",
				"wmi_app/Win32_MoveFileAction",
				"wmi_app/Win32_MSIResource",
				"wmi_app/Win32_ODBCAttribute",
				"wmi_app/Win32_ODBCDataSourceSpecification",
				"wmi_app/Win32_ODBCDriverSoftwareElement",
				"wmi_app/Win32_ODBCDriverSpecification",
				"wmi_app/Win32_ODBCSourceAttribute",
				"wmi_app/Win32_ODBCTranslatorSpecification",
				"wmi_app/Win32_Patch",
				"wmi_app/Win32_PatchPackage",
				"wmi_app/Win32_Product",
				"wmi_app/Win32_ProgIDSpecification",
				"wmi_app/Win32_Property",
				"wmi_app/Win32_PublishComponentAction",
				"wmi_app/Win32_RegistryAction",
				"wmi_app/Win32_RemoveFileAction",
				"wmi_app/Win32_RemoveIniAction",
				"wmi_app/Win32_ReserveCost",
				"wmi_app/Win32_SelfRegModuleAction",
				"wmi_app/Win32_ServiceControl",
				"wmi_app/Win32_ServiceSpecification",
				"wmi_app/Win32_ServiceSpecificationService",
				"wmi_app/Win32_ShortcutAction",
				"wmi_app/Win32_ShortcutSAP",
				"wmi_app/Win32_SoftwareElement",
				"wmi_app/Win32_SoftwareElementCondition",
				"wmi_app/Win32_SoftwareFeature",
				"wmi_app/Win32_SoftwareFeatureParent",
				"wmi_app/Win32_TypeLibraryAction",



				"wmi_perf/perf_fmt/Win32_PerfFormattedData",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_ASP_ActiveServerPages",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_ContentFilter_IndexingServiceFilter",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_ContentIndex_IndexingService",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_InetInfo_InternetInformationServicesGlobal",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_ISAPISearch_HttpIndexingService",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_MSDTC_DistributedTransactionCoordinator",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_NTFSDRV_SMTPNTFSStoreDriver",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfDisk_LogicalDisk",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfDisk_PhysicalDisk",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfNet_Browser",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfNet_Redirector",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfNet_Server",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfNet_ServerWorkQueues",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfOS_Cache",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfOS_Memory",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfOS_Objects",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfOS_PagingFile",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfOS_Processor",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfOS_System",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfProc_FullImage_Costly",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfProc_Image_Costly",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfProc_JobObject",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfProc_JobObjectDetails",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfProc_Process",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfProc_ProcessAddressSpace_Costly",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfProc_Thread",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PerfProc_ThreadDetails_Costly",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PSched_PSchedFlow",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_PSched_PSchedPipe",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_RemoteAccess_RASPort",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_RemoteAccess_RASTotal",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_RSVP_ACSRSVPInterfaces",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_RSVP_ACSRSVPService",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_SMTPSVC_SMTPServer",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_Spooler_PrintQueue",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_TapiSrv_Telephony",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_Tcpip_ICMP",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_Tcpip_IP",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_Tcpip_NBTConnection",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_Tcpip_NetworkInterface",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_Tcpip_TCP",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_Tcpip_UDP",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_TermService_TerminalServices",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_TermService_TerminalServicesSession",
				"wmi_perf/perf_fmt/Win32_PerfFormattedData_W3SVC_WebService",

				"wmi_perf/perf_raw/Win32_PerfRawData",
				"wmi_perf/perf_raw/Win32_PerfRawData_ASP_ActiveServerPages",
				"wmi_perf/perf_raw/Win32_PerfRawData_ContentFilter_IndexingServiceFilter",
				"wmi_perf/perf_raw/Win32_PerfRawData_ContentIndex_IndexingService",
				"wmi_perf/perf_raw/Win32_PerfRawData_InetInfo_InternetInformationServicesGlobal",
				"wmi_perf/perf_raw/Win32_PerfRawData_ISAPISearch_HttpIndexingService",
				"wmi_perf/perf_raw/Win32_PerfRawData_MSDTC_DistributedTransactionCoordinator",
				"wmi_perf/perf_raw/Win32_PerfRawData_NTFSDRV_SMTPNTFSStoreDriver",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfDisk_LogicalDisk",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfDisk_PhysicalDisk",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfNet_Browser",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfNet_Redirector",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfNet_Server",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfNet_ServerWorkQueues",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfOS_Cache",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfOS_Memory",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfOS_Objects",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfOS_PagingFile",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfOS_Processor",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfOS_System",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfProc_FullImage_Costly",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfProc_Image_Costly",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfProc_JobObject",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfProc_JobObjectDetails",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfProc_Process",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfProc_ProcessAddressSpace_Costly",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfProc_Thread",
				"wmi_perf/perf_raw/Win32_PerfRawData_PerfProc_ThreadDetails_Costly",
				"wmi_perf/perf_raw/Win32_PerfRawData_PSched_PSchedFlow",
				"wmi_perf/perf_raw/Win32_PerfRawData_PSched_PSchedPipe",
				"wmi_perf/perf_raw/Win32_PerfRawData_RemoteAccess_RASPort",
				"wmi_perf/perf_raw/Win32_PerfRawData_RemoteAccess_RASTotal",
				"wmi_perf/perf_raw/Win32_PerfRawData_RSVP_ACSRSVPInterfaces",
				"wmi_perf/perf_raw/Win32_PerfRawData_RSVP_ACSRSVPService",
				"wmi_perf/perf_raw/Win32_PerfRawData_SMTPSVC_SMTPServer",
				"wmi_perf/perf_raw/Win32_PerfRawData_Spooler_PrintQueue",
				"wmi_perf/perf_raw/Win32_PerfRawData_TapiSrv_Telephony",
				"wmi_perf/perf_raw/Win32_PerfRawData_Tcpip_ICMP",
				"wmi_perf/perf_raw/Win32_PerfRawData_Tcpip_IP",
				"wmi_perf/perf_raw/Win32_PerfRawData_Tcpip_NBTConnection",
				"wmi_perf/perf_raw/Win32_PerfRawData_Tcpip_NetworkInterface",
				"wmi_perf/perf_raw/Win32_PerfRawData_Tcpip_TCP",
				"wmi_perf/perf_raw/Win32_PerfRawData_Tcpip_UDP",
				"wmi_perf/perf_raw/Win32_PerfRawData_TermService_TerminalServices",
				"wmi_perf/perf_raw/Win32_PerfRawData_TermService_TerminalServicesSession",
				"wmi_perf/perf_raw/Win32_PerfRawData_W3SVC_WebService",
			};
		}

		// For all other namespaces
		return null;
	}
}
