// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.ixora.remote;

public final class HostManagerImpl_Stub
    extends java.rmi.server.RemoteStub
    implements com.ixora.remote.HostManager, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_createManaged_0;
    private static java.lang.reflect.Method $method_destroyManaged_1;
    private static java.lang.reflect.Method $method_getHostInfo_2;
    private static java.lang.reflect.Method $method_getOsName_3;
    private static java.lang.reflect.Method $method_ping_4;
    private static java.lang.reflect.Method $method_restart_5;
    private static java.lang.reflect.Method $method_shutdown_6;
    private static java.lang.reflect.Method $method_update_7;
    
    static {
	try {
	    $method_createManaged_0 = com.ixora.remote.HostManager.class.getMethod("createManaged", new java.lang.Class[] {java.lang.String.class, java.lang.String.class, com.ixora.remote.RemoteManagedListener.class});
	    $method_destroyManaged_1 = com.ixora.remote.HostManager.class.getMethod("destroyManaged", new java.lang.Class[] {com.ixora.remote.RemoteManaged.class});
	    $method_getHostInfo_2 = com.ixora.remote.HostManager.class.getMethod("getHostInfo", new java.lang.Class[] {});
	    $method_getOsName_3 = com.ixora.common.update.multinode.Updateable.class.getMethod("getOsName", new java.lang.Class[] {});
	    $method_ping_4 = com.ixora.common.remote.PingableRemote.class.getMethod("ping", new java.lang.Class[] {});
	    $method_restart_5 = com.ixora.common.update.multinode.Updateable.class.getMethod("restart", new java.lang.Class[] {});
	    $method_shutdown_6 = com.ixora.common.remote.Shutdownable.class.getMethod("shutdown", new java.lang.Class[] {});
	    $method_update_7 = com.ixora.common.update.multinode.Updateable.class.getMethod("update", new java.lang.Class[] {com.ixora.common.update.multinode.UpdatePart[].class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public HostManagerImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of createManaged(String, String, RemoteManagedListener)
    public com.ixora.remote.RemoteManaged createManaged(java.lang.String $param_String_1, java.lang.String $param_String_2, com.ixora.remote.RemoteManagedListener $param_RemoteManagedListener_3)
	throws com.ixora.remote.exception.RemoteManagedListenerIsUnreachable, com.ixora.rms.exception.RMSException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_createManaged_0, new java.lang.Object[] {$param_String_1, $param_String_2, $param_RemoteManagedListener_3}, -408891411539669533L);
	    return ((com.ixora.remote.RemoteManaged) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (com.ixora.rms.exception.RMSException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of destroyManaged(RemoteManaged)
    public void destroyManaged(com.ixora.remote.RemoteManaged $param_RemoteManaged_1)
	throws com.ixora.rms.exception.RMSException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_destroyManaged_1, new java.lang.Object[] {$param_RemoteManaged_1}, 645284456112370387L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (com.ixora.rms.exception.RMSException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getHostInfo()
    public com.ixora.rms.HostInformation getHostInfo()
	throws com.ixora.rms.exception.RMSException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getHostInfo_2, null, -5769210591876777035L);
	    return ((com.ixora.rms.HostInformation) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (com.ixora.rms.exception.RMSException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of getOsName()
    public java.lang.String getOsName()
	throws com.ixora.common.exception.AppException, java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getOsName_3, null, -7484209875218062221L);
	    return ((java.lang.String) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (com.ixora.common.exception.AppException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of ping()
    public void ping()
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_ping_4, null, 5866401369815527589L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of restart()
    public void restart()
	throws com.ixora.common.exception.AppException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_restart_5, null, -2563244869731757367L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (com.ixora.common.exception.AppException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of shutdown()
    public void shutdown()
	throws com.ixora.common.exception.AppException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_shutdown_6, null, -7207851917985848402L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (com.ixora.common.exception.AppException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of update(UpdatePart[])
    public void update(com.ixora.common.update.multinode.UpdatePart[] $param_arrayOf_UpdatePart_1)
	throws com.ixora.common.exception.AppException, java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_update_7, new java.lang.Object[] {$param_arrayOf_UpdatePart_1}, -2682863800862437567L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (com.ixora.common.exception.AppException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
