// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.ixora.jobs.remote;

public final class JobManagerEventHandler_Stub
    extends java.rmi.server.RemoteStub
    implements com.ixora.jobs.remote.JobManagerListener, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_jobLogEvent_0;
    private static java.lang.reflect.Method $method_jobStateEvent_1;
    
    static {
	try {
	    $method_jobLogEvent_0 = com.ixora.jobs.remote.JobManagerListener.class.getMethod("jobLogEvent", new java.lang.Class[] {com.ixora.jobs.JobLogEvent.class});
	    $method_jobStateEvent_1 = com.ixora.jobs.remote.JobManagerListener.class.getMethod("jobStateEvent", new java.lang.Class[] {com.ixora.jobs.JobStateEvent.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public JobManagerEventHandler_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of jobLogEvent(JobLogEvent)
    public void jobLogEvent(com.ixora.jobs.JobLogEvent $param_JobLogEvent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_jobLogEvent_0, new java.lang.Object[] {$param_JobLogEvent_1}, -5515571791437985305L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of jobStateEvent(JobStateEvent)
    public void jobStateEvent(com.ixora.jobs.JobStateEvent $param_JobStateEvent_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_jobStateEvent_1, new java.lang.Object[] {$param_JobStateEvent_1}, 1708401871178249938L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
