// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.ixora.rms.remote.agents;

public final class RemoteAgentManagerEventHandler_Stub
    extends java.rmi.server.RemoteStub
    implements com.ixora.rms.remote.agents.RemoteAgentManagerListener, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_monitoredEntitiesChanged_0;
    private static java.lang.reflect.Method $method_monitoringAgentNonFatalError_1;
    private static java.lang.reflect.Method $method_monitoringAgentStateChanged_2;
    private static java.lang.reflect.Method $method_receiveDataBuffers_3;
    
    static {
	try {
	    $method_monitoredEntitiesChanged_0 = com.ixora.rms.remote.agents.RemoteAgentManagerListener.class.getMethod("monitoredEntitiesChanged", new java.lang.Class[] {java.lang.String.class, com.ixora.rms.agents.AgentId.class, com.ixora.rms.EntityDescriptorTree.class});
	    $method_monitoringAgentNonFatalError_1 = com.ixora.rms.remote.agents.RemoteAgentManagerListener.class.getMethod("monitoringAgentNonFatalError", new java.lang.Class[] {java.lang.String.class, com.ixora.rms.agents.AgentId.class, java.lang.Throwable.class});
	    $method_monitoringAgentStateChanged_2 = com.ixora.rms.remote.agents.RemoteAgentManagerListener.class.getMethod("monitoringAgentStateChanged", new java.lang.Class[] {java.lang.String.class, com.ixora.rms.agents.AgentId.class, com.ixora.rms.agents.AgentState.class, java.lang.Throwable.class});
	    $method_receiveDataBuffers_3 = com.ixora.rms.remote.agents.RemoteAgentManagerListener.class.getMethod("receiveDataBuffers", new java.lang.Class[] {com.ixora.rms.agents.AgentDataBuffer[].class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RemoteAgentManagerEventHandler_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of monitoredEntitiesChanged(String, AgentId, EntityDescriptorTree)
    public void monitoredEntitiesChanged(java.lang.String $param_String_1, com.ixora.rms.agents.AgentId $param_AgentId_2, com.ixora.rms.EntityDescriptorTree $param_EntityDescriptorTree_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_monitoredEntitiesChanged_0, new java.lang.Object[] {$param_String_1, $param_AgentId_2, $param_EntityDescriptorTree_3}, -4590403564605033627L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of monitoringAgentNonFatalError(String, AgentId, Throwable)
    public void monitoringAgentNonFatalError(java.lang.String $param_String_1, com.ixora.rms.agents.AgentId $param_AgentId_2, java.lang.Throwable $param_Throwable_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_monitoringAgentNonFatalError_1, new java.lang.Object[] {$param_String_1, $param_AgentId_2, $param_Throwable_3}, -2713675280034138331L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of monitoringAgentStateChanged(String, AgentId, AgentState, Throwable)
    public void monitoringAgentStateChanged(java.lang.String $param_String_1, com.ixora.rms.agents.AgentId $param_AgentId_2, com.ixora.rms.agents.AgentState $param_AgentState_3, java.lang.Throwable $param_Throwable_4)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_monitoringAgentStateChanged_2, new java.lang.Object[] {$param_String_1, $param_AgentId_2, $param_AgentState_3, $param_Throwable_4}, 5399758122276631587L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of receiveDataBuffers(AgentDataBuffer[])
    public void receiveDataBuffers(com.ixora.rms.agents.AgentDataBuffer[] $param_arrayOf_AgentDataBuffer_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_receiveDataBuffers_3, new java.lang.Object[] {$param_arrayOf_AgentDataBuffer_1}, 8415620278249922432L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
