// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package com.ixora.rms.remote.providers;

public final class RemoteProviderManagerEventHandler_Stub
    extends java.rmi.server.RemoteStub
    implements com.ixora.rms.remote.providers.RemoteProviderManagerListener, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_data_0;
    private static java.lang.reflect.Method $method_providerStateChanged_1;
    
    static {
	try {
	    $method_data_0 = com.ixora.rms.remote.providers.RemoteProviderManagerListener.class.getMethod("data", new java.lang.Class[] {com.ixora.rms.providers.ProviderDataBuffer[].class});
	    $method_providerStateChanged_1 = com.ixora.rms.remote.providers.RemoteProviderManagerListener.class.getMethod("providerStateChanged", new java.lang.Class[] {com.ixora.rms.providers.ProviderId.class, com.ixora.rms.providers.ProviderState.class, java.lang.Throwable.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public RemoteProviderManagerEventHandler_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of data(ProviderDataBuffer[])
    public void data(com.ixora.rms.providers.ProviderDataBuffer[] $param_arrayOf_ProviderDataBuffer_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_data_0, new java.lang.Object[] {$param_arrayOf_ProviderDataBuffer_1}, -3277600342978211785L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of providerStateChanged(ProviderId, ProviderState, Throwable)
    public void providerStateChanged(com.ixora.rms.providers.ProviderId $param_ProviderId_1, com.ixora.rms.providers.ProviderState $param_ProviderState_2, java.lang.Throwable $param_Throwable_3)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_providerStateChanged_1, new java.lang.Object[] {$param_ProviderId_1, $param_ProviderState_2, $param_Throwable_3}, -2169566387004073552L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
