/*
 * Created on 13-Dec-2003
 */
package com.ixora.common.ui;

import java.awt.Frame;

/**
 * GUI exception handler. The GUI needs to differentiate between
 * exceptions generated by user or system as usually the user exceptions
 * will result in a popup dialog describing the error.
 * @author Daniel Moraru
 */
public interface UIExceptionHandler {
	/**
	 * Invoked when the exception handler must
	 * be notified of the given exception.
	 * @param e
	 */
	void exception(Throwable e);
	/**
	 * Signals a user exception. A user exception is generated
	 * by a user interaction with the GUI.
	 * @param e
	 */
	void userException(Throwable e);

    /**
     * Signals a user exception. A user exception is generated
     * by a user interaction with the GUI.
     * @param owner
     * @param e
     */
    void userException(Frame owner, Throwable e);
}
